### ISSUE TITLE
Desenvolvimento

### ISSUE THREAD

**Issue by rlrpara** [samuelrochaoliveira/SPEDBr-Standard#1]
Está ativo e em desenvolvimento?
Precisa de ajuda?

**Comment by orochasamuel** [comment]
Opa!! Fala @rlrpara tudo na paz?

Desculpa a demora em retornar.

Está ativo sim o projeto, neste mês de Dezembro irei atualizar os layouts para a versão de 2019, o SPED Fiscal e o Contribuições.

Toda ajuda é bem vinda. :)

Abraços.

**Comment by osnipezzini** [comment]
Boa tarde , o desenvolvimento não está mais ativo , correto ?

**Comment by orochasamuel** [comment]
Fala @osnipezzini tudo na paz?

Está sim, mas estou concentrando os esforços em outro repositório, o [FiscalBr](https://github.com/osamueloliveira/FiscalBr.NET).

Como estou muito ocupado por esses tempos está "congelado" mesmo. Mas qualquer novidade será incrementada nesse novo repositório. Até o final desse ano eu vou "aposentar" esse repositório do SPEDBr.

Qualquer dúvida chama aê. o/

**Comment by osnipezzini** [comment]
Boa tarde , acabei vendo seu repositório , mas seria interessante remover o acesso mesmo a esses pois gera conflito . Vou começar a contribuir com seu novo projeto também

**Comment by orochasamuel** [comment]
Eu mantive esse repositório pois o pacote Nuget foi gerado baseado nele.

Assim que eu fizer a criação de um pacote Nuget do outro projeto esse daqui poderá ser descartado.

Toda e qualquer contribuição será bem vinda.

**Comment by orochasamuel** [comment]
Fala @rlrpara @osnipezzini beleza?

O novo repositório já está em produção, para acessar [clique aqui](https://github.com/osamueloliveira/FiscalBr.NET).

Vida longa e próspera. 🖖
